### ISSUE TITLE
Doesn't load when wifi is turned off

### ISSUE THREAD

**Issue by SwiftWinds** [Anyass3/kit-sw-workbox#3]
I installed `kit-sw-workbox`, configured [my Svelte config](https://github.com/SwiftWinds/ucsb-covid-badge/blob/main/svelte.config.js) (I added `/` to the routes array), created [a service worker](https://github.com/SwiftWinds/ucsb-covid-badge/blob/main/src/service-worker.ts) based on the `Example service-worker file` from your README, and added code to [the `__layout.svelte`](https://github.com/SwiftWinds/ucsb-covid-badge/blob/main/src/routes/__layout.svelte) based on the `Example in your browser window code` from your README.

However, after loading the web app, waiting a bit, disabling wifi, and refreshing, it doesn't load. You can try it yourself: https://covidbadge.pages.dev.

Any ideas why?

**Comment by Anyass3** [comment]
Hi @SwiftWinds. Hmm let's see

**Comment by Anyass3** [comment]
It seems you already found a solution

**Comment by SwiftWinds** [comment]
Yeah, sorry I forgot to close this issue; I decided to just write a service worker from scratch
